services:
  spark-pipeline:
    build: ./docker
    container_name: spark_pipeline
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.9.1
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - .:/opt/airflow  # 👈 IMPORTANTE (todo el proyecto)
    ports:
      - "8080:8080"
    command: bash -c "airflow db init && airflow users create \
      --username admin \
      --password admin \
      --firstname mauricio \
      --lastname cerpa \
      --role Admin \
      --email mauriciochdataeng@gmail.com && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.9.1
    depends_on:
      - airflow-webserver
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - .:/opt/airflow
    command: scheduler

volumes:
  postgres-db-volume: