FROM python:3.10-slim-bullseye

# Installing Java (required for Spark)
RUN apt-get update && apt-get install -y \
    openjdk-11-jdk \
    curl \
    && apt-get clean

# JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Set working directory
WORKDIR /app

# Copy the project
COPY . .

# Copy requirements
# COPY requirements.txt .

RUN pip install pyspark==3.5.0 python-dotenv

CMD ["python", "scripts/pipeline.py"]